Queue-ri/Advanced-Algorithm-Study

- BOGGLE/Scaachan.cpp
> [Week 1] Solved BOGGLE - Scaachan

- FESTIVAL/hanjuuuuuu.cpp
출력 형식 실수
Replacement of: #38, #39
> [Week 1] Solved FESTIVAL - hanjuuuuuu

- FESTIVAL/dakyommii.cpp
> **DO NOT REFER ISSUE NUMBER by `#` TAG.**
> - [x] I titled `[Week <#>] Solved <problem> - <id>`
> - [x] I briefly explained how I got `AC` below.
> - [x] I assigned myself.
> - [x] I set `Scaachan` for reviewer.
> - [x] I linked previous self/peer reviews.
대여 시작일과 대여 일수를 for문으로 돌려 대여 시작일로부터 대여일수만큼 빌렸을 때의 평균을 계속 갱신하면서 최소값 구함
> [Week 1] Solved FESTIVAL - dakyommii

- PI/Yunhyunjo.cpp
> [Week 3] AC rebase merge

- BOGGLE/hanjuuuuuu.cpp
> [Week 1] Solved BOGGLE - hanjuuuuuu

- JUMPGAME/Yunhyunjo.cpp
- TILING2/Yunhyunjo.cpp
- TILING2/yujungee.cpp
> [Week 4] AC rebase merge

- BOGGLE/yujungee.cpp
> **DO NOT REFER ISSUE NUMBER by `#` TAG.**
> - [x] I titled `[week 1] Solved BOGGLE - yujungee`
> - [x] I briefly explained how I got `AC` below.
> - [x] I assigned myself.
> - [x] I set `Scaachan` for reviewer.
> - [x] I linked previous self/peer reviews.
> [Week 1] Solved BOGGLE - yujungee

- ASYMTILING/Scaachan.cpp
- PACKING/Scaachan.cpp
> [Week 5] AC rebase merge

- FESTIVAL/README.md
Squash merge update(s) from `festival-readme` branch.
Recreated `festival-readme` branch after squash merging #82, and cherry-picked `76c99f6` & `8b82f68`
since the previous branch had a conflict due to a squash merge.
> Update FESTIVAL/README.md : add solving status

- ABC/BOARDCOVER/Yunhyunjo.cpp
> **DO NOT REFER ISSUE NUMBER by `#` TAG.**
> - [x] I titled `[Week <#>] Solved <problem> - <id>`
> - [x] I briefly explained how I got `AC` below.
> - [x] I assigned myself.
> - [x] I set `Scaachan` for reviewer.
> - [x] I linked previous self/peer reviews.
> [Week 2] Solved BOARDCOVER - Yunhyunjo

- ABC/BOGGLE/README.md
Squash merge update(s) from `boggle-readme` branch.
> Update BOGGLE/README.md : add problem info

- DEF/DRAGON/dakyomii.cpp
- DEF/DRAGON/yujungee.cpp
> [Week 6] AC rebase merge

- STU/TRIPATHCNT/Yunhyunjo.cpp
> **DO NOT REFER ISSUE NUMBER by `#` TAG.**
> - [x] I titled `[Week <#>] Solved <problem> - <id>`
> - [x] I briefly explained how I got `AC` below.
> - [x] I assigned myself.
> - [x] I set `Scaachan` for reviewer.
> - [x] I linked previous self/peer reviews.
> [Week 4] Solved TRIPATHCNT - Yunhyunjo

- MNO/NUMBERGAME/hanjuuuuuu.cpp
> [Week 7] AC rebase merge

- MNO/MATCHORDER/hanjuuuuuu.cpp
- MNO/MATCHORDER/yujungee.cpp
> [Week 8] AC rebase merge

- PQR/PACKING/ChaeheeKang-Github.py
함수를 사용해서 시간 부족 문제를 해결하였습니다.
Closes #131
> [Week 2] Solved PACKING - ChaeheeKang-GitHub

- STU/TRIPATHCNT/ChaeheeKang-Github.py
삼각형을 거꾸로 타고 올라간다는 컨셉을 이해하고 
이에 따라 삼각형의 마지막 레벨의 초기화를 진행시켜 문제를 해결하였습니다.
Closes #132
> [Week 2] Solved TRIPATHCNT - ChaeheeKang-GitHub

- STU/TRIPATHCNT/profitjean.py
리뷰에서 작성해주신것처럼 
파이썬 functools의 lru_cache를 이용하여 시간초과문제를 해결하였습니다.
closes #133
> [Week 2] Solved TRIPATHCNT - profitjean

- PQR/PACKING/profitjean.py
가방에 담을 수 있는 최대 무게를 계산하는 부분까지 재귀함수로 따로 빼서 작성하였습니다. 
인덱스도 1부터 시작하여 인덱스 에러 문제를 해결했습니다.
closes #135
> [Week 2] Solved PACKING - profitjean

- PQR/PACKING/Yunhyunjo.cpp
짐을 계산하는 과정에서 잘못되었었고, 리뷰에 작성해 주신 것처럼 추적하는 코드를 따로 작성하여 해결했습니다.
Closes #136
> [Week 2] Solved PACKING - Yunhyunjo

- PQR/RUNNINGMEDIAN/Choi-mina.cpp
```cpp
int running_median() {
long long seed = 1983;
priority_queue<int, vector<int>, less<int>> maxHeap;
priority_queue<int, vector<int>, greater<int>> minHeap;
int sum = 1983;
maxHeap.push(seed);
for (int i = 1; i < N; i++) {
int now = ((seed * a) + b) % 20090711;
if (maxHeap.size() == minHeap.size())
maxHeap.push(now);
else
minHeap.push(now);
if (!minHeap.empty() && !maxHeap.empty() && minHeap.top() < maxHeap.top()) {
int top1 = maxHeap.top(), top2 = minHeap.top();
maxHeap.pop();
minHeap.pop();
maxHeap.push(top2);
minHeap.push(top1);
}
sum = (sum + maxHeap.top()) % 20090711;
seed = now;
sum %= 20090711;
}
return sum;
}
```
입력생성 조건을 이해하는데에서 막혔었는데 리뷰를 듣고 수정했습니다.
seed변수에 1983을, seed를 maxHeap에 먼저 넣어주고 1부터 반복문을 돌았습니다.
반복문을 돌면서 입력을 만들어줄 수 있도록 int now = ((seed * a) + b) % 20090711; 를 …
> [Week 3] Solved RUNNINGMEDIAN - Choi-mina

- PQR/PALINDROMIZE/ChaeheeKang-Github.py
LPS를 통해 문제를 해결하였습니다!
저번주에도 문제를 풀때 코드는 맞는것 같은데 오답이 나와 애를 먹었는는데 문제는 입력을 str(input())으로 받아줘서 그랬습니다...
입력은 input().rstrip()으로 받아줘야 오류없이 정답이 출력됩니다.
Closed #159
> [Week 4] Solved PALINDROMIZE - ChaeheeKang-GitHub

- JKL/JAEHASAFE/Choi-mina.cpp
```cpp
vector <int> match(const string& rs) {
vector<int> pi(rs.size(), 0);
int begin = 1, matched = 0;
while (begin + matched < rs.size()) {
// begin+matched에 있는 문자와 matched에 있는 문자가 같은 경우
if (rs[begin + matched] == rs[matched]) {
++matched;
pi[begin + matched - 1] = matched;
}
// 다른 경우
else {
// matched가 0인 경우에는 다음칸부터 계속해서 계산
if (matched == 0)
++begin;
else {
// 시작위치를 (matched - 일치하는 접두사와 접미사가 길이)만큼 빼서 이동
begin += matched - pi[matched - 1];
// begin을 옮기고 나서도 pi[matched - 1]만큼은 같으니까
// matched = pi[matched - 1]
matched = pi[matched - 1];
}
}
}
return pi;
}
int kmp(const string& s, const string& rs) {
vector <int> pi = match(rs);
int m = s.size(), n = rs.size();
int begin = 0, matched = 0;
while (begin <= m - n) {
// s의 글자가 rs의 글자와 같은 경우
if (s[begin + matched] == rs[matched]) {
++matched; …
```
> [Week 4] Solved JAEHASAFE - Choi-mina

- JKL/JAEHASAFE/Yunhyunjo.cpp
shift함수로 넘길때 문자열을 두배로 해서 넘겨주고 실패함수로 얻은 값으로 빠르게 어디에 위치하는지 탐색하여 그 위치를 반환해 주었습니다.
Closes #164
> [Week 4] Solved JAEHASAFE - Yunhyunjo

- PQR/PALINDROMIZE/profitjean.py
설명해주셨던것처럼 
for문을 활용한 reverse 문자열 변환 대신, 문자열 슬라이싱으로 변경하고, 
len_palindrome 매칭과정도 제거하였습니다.
더 단순하게 접근할 수 있었던 문제였던것같은데 너무 돌아갔었던것 같습니다😥
closes #160
> [Week 4] Solved PALINDROMIZE - profitjean

- DEF/FORTRESS/Choi-mina.cpp
```cpp
//성벽 a가 성벽 b를 포함하는지 확인
bool enclose(int a, int b) {
if (r[a] > r[b]) {
int dx = x[a] - x[b];
int dy = y[a] - y[b];
if (pow(dx, 2) + pow(dy, 2) < pow(r[a] - r[b], 2))
return true;
}
return false;
}
// parent는 child를 꼭 직접 포함해야 한다.
bool isChild(int parent, int child) {
if (!enclose(parent, child)) return false;
for (int i = 0; i < N; i++)
if (i != parent && i != child &&
enclose(parent, i) && enclose(i, child))
return false;
return true;
}
```
parent가 child의 부모인지 확인하는 함수입니다. 
enclose 함수를 통해 a가 b를 포함하는지 확인하고 포함하지 않는다면 isChild에서 false를 반환합니다.
```cpp
// 서브트리가 2개 이상인 경우
if (heights.size() >= 2)
longest = max(longest, 2 + heights[heights.size() - 2] + heights[heights.size() - 1]);
```
서브트리가 2개 이상인 경우에서 막혔는데
서브트리가 2개 이상이라는 것은 자식이 여러개라는 뜻이므로
현재 노드를 최상위 노드로 하는 leaf-leaf 경로 중 가장 긴 것을  max에 …
> [Week 5] Solved FORTRESS - Choi-mina

- JKL/JAEHASAFE/profitjean.py
kmp 알고리즘 대신 문자열 비교 풀이를 활용했습니다.
리뷰 달아주셨던것처럼 문자열 슬라이싱으로 일치연산을 진행해볼 수 있었습니다.
closes #163
> [Week 4] Solved JAEHASAFE - profitjean
